#Python script to modify Gcode to repeat prints on the Lulzbot TAZ 6 
#To use, make sure to have the Gcode file generated by Cura in the
#same folder as this script, init.txt, and iter.txt. To initialize the
#scraper, begin the code with the entire edge of the freely hanging
#scraper in contact with the heated bed. Try to make it rest lightly.
#In order for the code to execute properly, all commands disabling stepper
#motors, cooling fans, or the hot end must be commented out in the desired
#gCode before running this script. Nothing can be disabled until this script
#is executed, appending the code with one complete disable all signal.

name = str(input("What is the name of the file generated by Cura?: "))
count = int(input("How many repetitions do you want?: "))
i = 0

#Read the code generated by Cura to memory
file = open(name,"r")
code = file.read()
file.close()
file = open('init.txt',"r")
pre = file.read()
file.close()
file = open('iter.txt',"r")
post = file.read()
file.close()

#Clear the file
file = open(name,"w")
file.write("")
file.close()

#Open the file and write Gcode
file = open(name,"a")
file.write(pre)#Add a block of code to initalize the setup
while i < count:
   
   #Write the code generated by Cura
   file.write(code)
   
   #Add a block of Gcode to clear the bed with the scraper
   file.write(post)
   
   #Alternate Gcode block to allow for use with unmodified printers
   #file.write("\n;clear the part off the bed\n")
   #file.write("G1 Y190 Z28\nM0 Remove Print and Click to Continue\n\n")
   
   i += 1

#Add a block of code to cool down and disable further movement
file.write("\n;Cool down, disable further movement, and end code\nM104 S0\n")
file.write("M107\n")
file.write("M84\n")
file.write("M104 S0\n")
file.close()
