#Python script to modify Gcode to repeat prints on the Lulzbot TAZ 6 
#To use, make sure to have the Gcode file generated by Cura in the same folder as the script

name = str(input("What is the name of the file generated by Cura?: "))
count = int(input("How many repetitions do you want?: "))
i = 0

#Read the code generated by Cura to memory
file = open(name,"r")
code = file.read()
file.close()

#Clear the file
file = open(name,"w")
file.write("")
file.close()

#Open the file and write Gcode
file = open(name,"a")
while i < count:
   
   #Write the code generated by Cura
   file.write(code)
   
   #Add a block of Gcode to clear the bed with the scraper, requires the scraper to start ~8.5in above the bed
   file.write("\n;clear the part off the bed\n")
   file.write("T0\nM82\nG92 E00\nG1 E100 F400\nG0 Y275\nG1 E-100 F400\n\n")
   
   #Alternate Gcode block to allow for use with unmodified printers
   #file.write("\n;clear the part off the bed\n")
   #file.write("G28\nG1 Y190 Z28\nM0 Remove Print and Click to Continue\n\n")
   
   i += 1
file.close()
